eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  #  这个的意思是随机指定个没使用的端口
  port:  ${PORT:${SERVER_PORT:0}}

---
  spring:
    profiles: subject
  words: I,You,He,She,It
---
  spring:
    profiles: verb
  words: ran,knew,had,saw,bought
---
  spring:
    profiles: article
  words: a,the
---
  spring:
    profiles: adjective
  words: reasonable,leaky,suspicious,ordinary,unlikely
---
  spring:
    profiles: noun
  words: boat,book,vote,seat,backpack,partition,groundhog
